import AppKit
import Combine

@MainActor
class ClipboardMonitor: ObservableObject {
    private var timer: AnyCancellable?
    private let clipboard = PasteboardService.shared
    private var lastChangeCount: Int

    /// Serialises every ingest: one item fully persisted before the next
    /// starts, so history order always matches copy order.
    ///
    /// `lazy` rather than built in `init`, because the pipeline's closure
    /// captures `self`. An implicitly-unwrapped `var` also worked, but then
    /// `Task { [pipeline] in }` captures a plain Optional and every call site
    /// has to unwrap it.
    private lazy var pipeline = IngestionPipeline { [weak self] kind, sourceApp in
        await self?.persist(kind, sourceApp: sourceApp)
    }

    init() {
        self.lastChangeCount = clipboard.changeCount
    }

    /// Starts the poll loop. Deliberately NOT called from `init`: the app must
    /// win the single-instance claim before this process touches the pasteboard
    /// or the shared database. Safe to call twice.
    func start() {
        guard timer == nil else { return }
        startMonitoring()
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }
    
    private func startMonitoring() {
        timer = Timer.publish(every: 0.5, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                self?.checkForChanges()
            }
    }
    
    private func checkForChanges() {
        guard clipboard.changeCount != lastChangeCount else { return }
        lastChangeCount = clipboard.changeCount

        // Skip changes written by the app itself (pasting from history),
        // otherwise re-encoded images would create duplicate entries
        // Any write that isn't the stack's own pauses the stack — including the
        // app's other self-writes (text capture, Copy Text, single-item paste),
        // which the gate below would hide. The service compares changeCounts
        // itself, so the stack's own writes never trigger a pause.
        PasteStackService.shared.noteClipboardChange()

        if clipboard.isSelfWrite(changeCount: lastChangeCount) {
            return
        }

        processClippedContent()
    }
    
    // De-facto standard markers (nspasteboard.org) that password managers and
    // other apps use to flag content a clipboard manager must not persist
    nonisolated static let sensitivePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    nonisolated static func containsSensitiveMarker(_ types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }
        return types.contains { sensitivePasteboardTypes.contains($0.rawValue) }
    }

    private func processClippedContent() {
        // Skip content the source app marked as concealed/transient
        // (passwords from 1Password, Keychain autofill, etc.)
        if Self.containsSensitiveMarker(clipboard.types) {
            return
        }

        // Find the source application
        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontmostApp?.localizedName
        let bundleID = frontmostApp?.bundleIdentifier

        // Check blacklist
        if BlacklistManager.shared.shouldIgnore(bundleID: bundleID) {
            return
        }

        // Read on the main actor, before anything can change the pasteboard.
        // The type-priority ladder and its lazy blob reads live in
        // PasteboardService.read() — one canonical order for the whole app.
        var payload = clipboard.read()
        payload.sourceApp = sourceApp

        // One ordered hand-off. Previously this spawned an independent
        // Task.detached per tick; those are unordered and the image branch's
        // decode outlives the 0.5s poll interval, so a later text copy could
        // land above an earlier image copy in history.
        Task { [pipeline] in
            await pipeline.submit(payload)
        }
    }

    /// Persists one classified payload and kicks off its background analysis.
    /// Runs serialised by `IngestionPipeline`, one item at a time, in copy order.
    @MainActor
    private func persist(_ kind: IngestKind, sourceApp: String?) async {
        switch kind {
        case .file(let paths):
            saveItem(type: "file", content: paths, sourceApp: sourceApp)
        case .color(let text):
            saveItem(type: "color", content: text, sourceApp: sourceApp)
        case .text(let text):
            saveItem(type: "text", content: text, sourceApp: sourceApp)
        case .rtf(let data):
            saveItem(type: "rtf", data: data, sourceApp: sourceApp)
        case .image(let data):
            let newItem = saveItem(type: "image", data: data, sourceApp: sourceApp)
            let itemID = newItem.id
            AIService.shared.performOCR(on: data) { text in
                if let text = text, !text.isEmpty {
                    Task { @MainActor in
                        if ClipboardStore.shared.items.contains(where: { $0.id == itemID }) {
                            ClipboardStore.shared.updateItem(id: itemID, content: text)
                        }
                    }
                }
            }
        case .none:
            break
        }
    }
    
    @discardableResult
    private func saveItem(type: String, content: String? = nil, data: Data? = nil, sourceApp: String? = nil) -> ClipboardItem {
        // Compare blobs via hash to avoid byte-by-byte Data comparisons
        let incomingHash = data.map(ClipboardItem.hash(of:))

        if let duplicate = ClipboardIngestion.recentDuplicate(
            in: ClipboardStore.shared.items, type: type, content: content, dataHash: incomingHash, now: Date()
        ) {
            return duplicate
        }

        let newItem = ClipboardItem(type: type, content: content, data: data, sourceApp: sourceApp)
        ClipboardStore.shared.addItem(newItem)

        // Heavy background analysis
        let capturedContent = content
        let capturedItemID = newItem.id

        Task.detached(priority: .background) {
            var detectedTags: [String] = []
            var detectedEmbedding: Data?

            if let text = capturedContent {
                detectedTags = ClipboardIngestion.detectTags(in: text)

                if text.count >= 3 && text.count <= 2000 {
                    if let vector = await AIService.shared.generateEmbedding(for: text) {
                        detectedEmbedding = ClipboardItem.encodeVector(vector)
                    }
                }

                // Update item with tags and embedding if changed
                if !detectedTags.isEmpty || detectedEmbedding != nil {
                    await ClipboardStore.shared.applyDetectedMetadata(
                        id: capturedItemID,
                        tags: detectedTags,
                        embedding: detectedEmbedding
                    )
                }
            }
        }

        return newItem
    }
}
