import AppKit
import Combine

@MainActor
class ClipboardMonitor: ObservableObject {
    private var timer: AnyCancellable?
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    
    init() {
        self.lastChangeCount = pasteboard.changeCount
        startMonitoring()
    }
    
    private func startMonitoring() {
        timer = Timer.publish(every: 0.5, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                self?.checkForChanges()
            }
    }
    
    private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Skip changes written by the app itself (pasting from history),
        // otherwise re-encoded images would create duplicate entries
        // Any write that isn't the stack's own pauses the stack — including the
        // app's other self-writes (text capture, Copy Text, single-item paste),
        // which the gate below would hide. The service compares changeCounts
        // itself, so the stack's own writes never trigger a pause.
        PasteStackService.shared.noteClipboardChange()

        if PasteboardSelfWriteGate.shared.isSelfWrite(changeCount: lastChangeCount) {
            return
        }

        processClippedContent()
    }
    
    // De-facto standard markers (nspasteboard.org) that password managers and
    // other apps use to flag content a clipboard manager must not persist
    nonisolated static let sensitivePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    nonisolated static func containsSensitiveMarker(_ types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }
        return types.contains { sensitivePasteboardTypes.contains($0.rawValue) }
    }

    private func processClippedContent() {
        // Skip content the source app marked as concealed/transient
        // (passwords from 1Password, Keychain autofill, etc.)
        if Self.containsSensitiveMarker(pasteboard.types) {
            return
        }

        // Find the source application
        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontmostApp?.localizedName
        let bundleID = frontmostApp?.bundleIdentifier

        // Check blacklist
        if BlacklistManager.shared.shouldIgnore(bundleID: bundleID) {
            return
        }

        // Extract data immediately on main thread to avoid pasteboard state changes,
        // but lazily in priority order — each data(forType:) copies the whole blob,
        // so never touch the multi-MB TIFF/PNG types when text already matched
        // fileURLsOnly: a copied browser URL must not be mistaken for a file
        let fileURLs = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL]
        let hasFiles = !(fileURLs?.isEmpty ?? true)
        let stringContent = hasFiles ? nil : pasteboard.string(forType: .string)
        let rtfData = (hasFiles || stringContent != nil) ? nil : pasteboard.data(forType: .rtf)
        let pngData = (hasFiles || stringContent != nil || rtfData != nil) ? nil : pasteboard.data(forType: .png)
        let tiffData = (hasFiles || stringContent != nil || rtfData != nil || pngData != nil) ? nil : pasteboard.data(forType: .tiff)

        Task.detached(priority: .userInitiated) {
            // 1. Check for Files FIRST — Finder also puts the file name on the
            // pasteboard as plain text, so checking text first would shadow
            // every file copy and record it as a text item
            if let urls = fileURLs, !urls.isEmpty {
                let paths = urls.map { $0.path }.joined(separator: "\n")
                await self.saveItemAsync(type: "file", content: paths, sourceApp: sourceApp)
            }
            // 2. Check for Text
            else if let text = stringContent {
                if self.isColor(text) {
                    await self.saveItemAsync(type: "color", content: text, sourceApp: sourceApp)
                } else {
                    await self.saveItemAsync(type: "text", content: text, sourceApp: sourceApp)
                }
            }
            // 3. Check for RTF
            else if let data = rtfData {
                await self.saveItemAsync(type: "rtf", data: data, sourceApp: sourceApp)
            }
            // 4. Check for Images
            else if let rawImageData = pngData ?? tiffData {
                // TIFF from the pasteboard is uncompressed (tens of MB per screenshot);
                // normalize to PNG before storing
                let imageData = Self.normalizedImageData(rawImageData) ?? rawImageData
                let newItem = await self.saveItemAsync(type: "image", data: imageData, sourceApp: sourceApp)

                // Perform OCR in background
                let itemID = newItem.id
                AIService.shared.performOCR(on: imageData) { text in
                    if let text = text, !text.isEmpty {
                        Task { @MainActor in
                            if ClipboardStore.shared.items.contains(where: { $0.id == itemID }) {
                                ClipboardStore.shared.updateItem(id: itemID, content: text)
                            }
                        }
                    }
                }
            }
        }
    }
    
    nonisolated private static func normalizedImageData(_ raw: Data) -> Data? {
        // Already PNG? Keep as-is
        if raw.starts(with: [0x89, 0x50, 0x4E, 0x47]) { return raw }
        guard let rep = NSBitmapImageRep(data: raw) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    @discardableResult
    private func saveItemAsync(type: String, content: String? = nil, data: Data? = nil, sourceApp: String? = nil) async -> ClipboardItem {
        // Compare blobs via hash to avoid byte-by-byte Data comparisons
        let incomingHash = data.map(ClipboardItem.hash(of:))

        // Deduplication check on MainActor
        return await MainActor.run {
            let now = Date()
            let recentItemsSnapshot = Array(ClipboardStore.shared.items.prefix(10))

            for recentItem in recentItemsSnapshot {
                if recentItem.type == type && recentItem.content == content && recentItem.dataHash == incomingHash {
                    let timeDiff = now.timeIntervalSince(recentItem.createdAt)
                    if timeDiff < 5.0 { return recentItem }
                }
            }

            let newItem = ClipboardItem(type: type, content: content, data: data, sourceApp: sourceApp)
            ClipboardStore.shared.addItem(newItem)
            
            // Heavy background analysis
            let capturedContent = content // Capturing for the task below
            let capturedItemID = newItem.id
            
            Task.detached(priority: .background) {
                var detectedTags: [String] = []
                var detectedEmbedding: Data?

                if let text = capturedContent {
                    detectedTags = self.detectTags(in: text)
                    
                    if text.count >= 3 && text.count <= 2000 {
                        if let vector = await AIService.shared.generateEmbedding(for: text) {
                            detectedEmbedding = ClipboardItem.encodeVector(vector)
                        }
                    }
                    
                    // Update item with tags and embedding if changed
                    if !detectedTags.isEmpty || detectedEmbedding != nil {
                        await ClipboardStore.shared.updateMetadata(
                            id: capturedItemID,
                            tags: detectedTags,
                            embedding: detectedEmbedding
                        )
                    }
                }
            }
            
            return newItem
        }
    }
    
    private func updateItemContent(id: UUID, content: String) {
        ClipboardStore.shared.updateItem(id: id, content: content)
    }
    
    nonisolated private func detectTags(in text: String) -> [String] {
        var tags: [String] = []
        
        // URL detection
        if let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) {
            let matches = detector.matches(in: text, range: NSRange(text.startIndex..., in: text))
            if !matches.isEmpty {
                tags.append("URL")
            }
        }
        
        // Email detection
        if text.contains("@") && text.contains(".") {
            let emailPattern = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
            if let _ = text.range(of: emailPattern, options: .regularExpression) {
                tags.append("Email")
            }
        }
        
        // Phone number detection (simple pattern)
        let phonePattern = "\\b\\d{3}[-.]?\\d{3,4}[-.]?\\d{4}\\b"
        if let _ = text.range(of: phonePattern, options: .regularExpression) {
            tags.append("Phone")
        }
        
        // Code detection (contains common programming keywords or symbols)
        let codeIndicators = ["func ", "class ", "def ", "import ", "const ", "let ", "var ", "function ", "=>", "->", "public ", "private "]
        if codeIndicators.contains(where: { text.contains($0) }) {
            tags.append("Code")
        }
        
        // JSON detection
        if (text.hasPrefix("{") && text.hasSuffix("}")) || (text.hasPrefix("[") && text.hasSuffix("]")) {
            if let _ = try? JSONSerialization.jsonObject(with: Data(text.utf8)) {
                tags.append("JSON")
            }
        }
        
        return tags
    }
    
    nonisolated private func isColor(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let hexPattern = "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}|[A-Fa-f0-9]{8})$"
        let rgbPattern = #"^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)$"#
        
        return trimmed.range(of: hexPattern, options: .regularExpression) != nil ||
               trimmed.range(of: rgbPattern, options: .regularExpression) != nil
    }
}
